LlamaServerport=8080
LlmModelName=doa.gguf
ToolDirectory=toolDir
LlamaCppDir=llamaCpp
LlamaCppBinaryDownlaodURL=http://localhost:8080/llama-server.zip
rootDir=/root
rootDirFromLocalDir=/data/user/0/com.rk.terminal.debug/local/alpine/root/
setUpFileName=setup.sh
remoteServerURL=http://10.211.101.161:8000
toolsWrapperFilePath=/root/ToolsWrapper
llmFilePath=/root/llmModels